name: luvpark
description: A new Flutter project.

publish_to: "none"  

version: 1.23.35+36
# updated version

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2  
  image_picker: ^1.0.2
  auto_size_text: ^3.0.0
  google_fonts: ^4.0.4
    
  # pattern_formatter: ^3.0.0
  
  qr_flutter:
    git:
      url: https://github.com/theyakka/qr.flutter.git
  mask_text_input_formatter: ^2.4.0 
  intl: ^0.19.0 

  flutter_multi_formatter: ^2.4.1
  shimmer: ^3.0.0  
  sizer: ^2.0.15
  shared_preferences: ^2.0.15  
  page_transition: ^2.0.9  
  flutter_dialogs: ^3.0.0
  pinput: ^4.0.0   
  app_settings: ^5.0.0 
  
  
  encrypt: ^5.0.0
  cryptography: ^2.5.0
  http: ^0.13.4 
  url_launcher: ^6.1.11
  webview_flutter_wkwebview: ^3.2.3
  webview_flutter_android: ^3.4.3
  webview_flutter: ^4.0.7
  animate_do: ^3.0.2
  local_auth: ^2.1.6
  percent_indicator: ^4.2.3
  device_apps: ^2.2.0
  external_app_launcher: ^3.1.0
  gallery_saver: ^2.3.2
  screenshot: ^2.1.0
  encrypted_shared_preferences: ^3.0.1
  location_geocoder: ^1.0.5
  geocoding: ^2.1.0   
  
  google_maps_flutter: ^2.5.0  
  flutter_google_places: ^0.3.0 
  google_api_headers: ^1.3.0 
  dropdown_button2: ^2.3.6   
  share_plus: ^7.2.1
  image: ^4.0.17
  permission_handler: ^11.0.0 
  sqflite: ^2.3.0 
  timezone: ^0.9.2 
  device_info_plus: ^9.1.1 
  email_validator: ^2.1.17   
  flutter_rating_bar: ^4.0.1
  flutter_xlider: ^3.5.0
  path_provider: ^2.1.1
  dart_ping: ^9.0.1
  dart_ping_ios: ^4.0.2
  google_maps_webservice: ^0.0.20-nullsafety.5
  flutter_polyline_points: ^1.0.0 
  get: ^4.6.6
  flutter_dotenv: ^5.1.0
 
  google_directions_api: ^0.9.1 
  google_places_for_flutter: ^1.0.1
  google_maps_utils: ^2.0.0+1 
  flutter_html: ^3.0.0-beta.2
  flutter_math_fork: ^0.7.2
  upgrader: ^9.0.0
  flutter_speed_dial: ^7.0.0 
  awesome_notifications: ^0.9.2    
  sliding_up_panel: ^2.0.0+1  
  iconsax: ^0.0.8
  colorful_safe_area: ^1.0.0
  wave_divider: ^0.0.3   
  calendar_date_picker2: ^0.5.5  
  # background_locator_2: ^2.0.6
  font_awesome_flutter: ^10.7.0
  clipboard: ^0.1.3
  carousel_slider: ^4.2.1
  rive: ^0.13.2
  dotted_border: ^2.1.0
  label_marker: ^1.0.1
  flutter_timezone: ^1.0.8
  flutter_dash: ^1.0.0
  flutter_image_compress: ^2.3.0 
  location: ^6.0.2
   
  
  
dev_dependencies:
  flutter_test:
    sdk: flutter 
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - assets/lottie/
    - assets/images/
    - assets/gif/
    - assets/ 
    - packages/timezone/data/latest.tzf
    - assets/custom_map_style/map_style.json

  fonts:  
    - family: SFProTextHeavy
      fonts:
        - asset: fonts/SF-Pro-Text-HeavyItalic.otf
    - family: SFProText
      fonts:
        - asset: fonts/SF-Pro-Italic.ttf

    - family: SFProTextReg
      fonts:
        - asset: fonts/SF-Pro-Text-Regular.otf
    - family: DMSans
      fonts:
        - asset: fonts/DMSans-VariableFont_opsz,wght.ttf
        